#!/bin/bash
# Generates Sources/BrushLLMPlayer/Core/Localization/GeneratedStrings.swift from
# Resources/*.lproj/Localizable.strings.
#
# Embedding the tables in the binary removes all localization file access at
# runtime: no SPM resource bundle, no CFBundleCreate during launch. The .strings
# files remain the editable source of truth — rerun this script after editing
# them (build-app.sh does it automatically).

set -euo pipefail
cd "$(dirname "$0")/.."

RESOURCES="Sources/BrushLLMPlayer/Resources"
OUTPUT="Sources/BrushLLMPlayer/Core/Localization/GeneratedStrings.swift"

# All languages shipped in the product, in the required order.
LANGS=("de" "en" "es" "fr" "pt-BR" "ja" "zh-Hans" "zh-Hant" "ko")

swift_dict() {
    local file="$1"
    /usr/bin/plutil -convert json -o - "$file" | /usr/bin/python3 -c '
import json, sys
table = json.load(sys.stdin)
print("[")
for key in sorted(table):
    value = table[key].replace("\\", "\\\\").replace("\"", "\\\"")
    key = key.replace("\\", "\\\\").replace("\"", "\\\"")
    print(f"    \"{key}\": \"{value}\",")
print("]")
'
}

{
    echo "// Generated by scripts/generate-localizable.sh — do not edit."
    echo "// Source of truth: Sources/BrushLLMPlayer/Resources/<lang>.lproj/Localizable.strings"
    echo ""
    echo "/// Embedded localization tables, keyed by language code."
    echo "enum GeneratedStrings {"
    echo "    static let tables: [String: [String: String]] = ["
    for lang in "${LANGS[@]}"; do
        file="$RESOURCES/$lang.lproj/Localizable.strings"
        if [ ! -f "$file" ]; then
            echo "error: missing $file" >&2
            exit 1
        fi
        echo "        \"$lang\": $(swift_dict "$file" | tr '\n' ' ' | sed 's/  */ /g'),"
    done
    echo "    ]"
    echo "}"
} > "$OUTPUT"

echo "generated $OUTPUT"
